pizzamama/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.first_page, name="firstpage"),
]

pizzamama/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls'))
]

pizzamama/main/models.py
from django.db import models

# Create your models here.

pizzamama/menu/models.py
from django.db import models


# Création des modèles.

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegan = models.BooleanField(default=False)

    def __str__(self):
        return self.name

pizzamama/main/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def first_page(request):
    return render(request, 'firstpage/first_page.html')

pizzamama/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza


# Create your views here.
def index(request):
    # pizzas = Pizza.objects.all()
    # pizzas_list = [f"{pizza.name} : {pizza.price} €" for pizza in pizzas]
    # pizzas_list_str = ", ".join(pizzas_list)
    # return HttpResponse(f"Les menus : {pizzas_list_str}")
    pizzas = Pizza.objects.all().order_by("name")
    return render(request, 'menu/index.html', {
                                                                                "pizzas": pizzas
    })

pizzamama/main/templates/firstpage/first_page.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Acceuil - PizzaMama</title>
        <link rel="stylesheet" href="{% static 'firstpage/style.css' %}">
    </head>
    <body>
        <div class="main-logo">
            <img src="{% static 'firstpage/images/main_logo.png' %}" alt="main_logo">
            <a href="{% url 'menu:index' %}">Voir le menu</a>
        </div>
    </body>
</html>

pizzamama/menu/templates/menu/index.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Menu - PizzaMama</title>
        <link rel="stylesheet" href="{% static 'menu/style.css' %}">
    </head>

    <body>
        <a href="{% url 'main:firstpage' %}">
            <img id="small-logo" src="{% static 'menu/images/small_logo.png' %}" alt="small_logo">
        </a>

        <div class="menu-title">
            <h1>Liste des pizzas</h1>
        </div>
        
        <div class="menu-list">
            {% for pizza in pizzas %}
                <div class="menu-list-items">
                    <span class="menu-list-title">{{ pizza.name }}</span> 
                    <span class="menu-list-number">{{ pizza.price | floatformat:2}}€</span>
                    <span class="menu-list-text">{{ pizza.ingredients }}</span>
                    {% if pizza.vegan %}
                        <span class="menu-list-bool">VÉGÉTARIENNE</span>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </body>
</html>